Optionsmecano = {}
Optionsmecano.command = 'mecano'                      -- configure the commande name /...
Optionsmecano.model = 'S_M_Y_DockWork_01'             -- configure the model ped for mecano
Optionsmecano.jobname = 'mechanic'                    -- configure the mechanic job name
Optionsmecano.max = 0                                 -- configure the maximum of mechanic worker to activate the command
Optionsmecano.timerwait = 30000                       -- configure how many times in ms the player wait the mecano 
Optionsmecano.timerrepair = 60000                     -- configure how many times during the repair 
Optionsmecano.cost = 1500                             -- configure the cost of the repair
Optionsmecano.body = true                             -- configure if mecano repair body (true | false)
Optionsmecano.addfuel = false                          -- configure if mecano add fuel (true | false)
Optionsmecano.fuellevel = 10.0                          -- configure add fuel level